---
title: "Albacore MSE"
subtitle: "Summary Plots"
author: "Laurie"
date: "05/04/2015"
output: word_document
---

```{r, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, fig.width =6, 
                           fig.height=4,
                           fig.path  ="../tex",
                           warning=FALSE, 
                           message=FALSE, 
                           error  =FALSE, 
                           echo   =FALSE,
                           cache  =!FALSE)
```

```{r}
library(FLCore)
library(ggplotFL)
library(reshape)
library(plyr)
library(kobe)
library(FLBRP)
library(lh)
library(biodyn)
library(popbio)
library(diags)

av=diags:::av

theme_set(theme_bw(base_size=10))

dirDat="/home/laurie/MEGAsync/mse/albn/data"

load(paste(dirDat,"/om.RData",  sep=""))
load(paste(dirDat,"/res1.RData",sep=""))
```

```{r}
pMeas=function(stk,brp,proxy="msy"){
  
  res=FLQuants(stock  =stock(stk)%/%FLBRP:::refpts(brp)[proxy,"biomass"],
               ssb    =ssb(  stk)%/%FLBRP:::refpts(brp)[proxy,"ssb"],
               rec    =rec(  stk)%/%FLBRP:::refpts(brp)[proxy,"rec"],
               catch  =catch(stk)%/%FLBRP:::refpts(brp)[proxy,"yield"],
               fbar   =fbar( stk)%/%FLBRP:::refpts(brp)[proxy,"harvest"],
               harvest=(catch(stk)/stock(stk))%/%(FLBRP:::refpts(brp)[proxy,"yield"]/FLBRP:::refpts(brp)[proxy,"biomass"]))
  
  model.frame(res,drop=T)}

pM<-function(om,eql){
  dat=pMeas(om,eql)

  res=with(dat, cbind(kobeSmry(stock,harvest),
                      dRate(catch,0),
                      dRate(catch,0.05),
                      dRate(catch,0.10),
                      diags:::av(catch),
                      diags:::av(harvest)))
  
  names(res)[10:14]=c("catch","catch5","catch10","aavCatch","aavF")
  res}


#seq(dims(x)[["minyear"]],dims(x)[["maxyear"]],3)
```

```{r,eval=FALSE}
f    =FLQuant(c(FLBRP:::refpts(eql[[1]])["msy","harvest"]),
                    dimnames=list(year=2007:2040))
srDev=rlnorm(500,f[,,,,1]*0,.3)
cFac=mlply(seq(0,1.5,.01), function(x){
      print(x)
      window(fwd(fwdWindow(om[[1]],end=2040,eql[[1]]),
                      f=f*x,sr=eql[[1]],sr.residuals=srDev),start=2010)})

pareto=ldply(cFac, pM, eql=eql[[1]])

save(cFac,file=paste(dirDat,"cFac.RData",sep="/"))
save(pareto,file=paste(dirDat,"pareto.RData",sep="/"))
```

```{rrun,eval=FALSE}
catch=FLQuant(c(FLBRP:::refpts(eql[[1]])["msy","yield"]),
                    dimnames=list(year=2007:2040))

yFac=mlply(seq(0,.9,.01), function(x){
      print(x)
      window(fwd(fwdWindow(om[[1]],end=2040,eql[[1]]),
                      catch=catch*x,sr=eql[[1]],sr.residuals=srDev),start=2010)})

paretoTAC=ldply(yFac, pM, eql=eql[[1]])

save(yFac,file=paste(dirDat,"yFac.RData",sep="/"))
save(paretoTAC,file=paste(dirDat,"paretoTAC.RData",sep="/"))
```

```{r}
load(paste(dirDat,"cFac.RData",sep="/"))
load(paste(dirDat,"yFac.RData",sep="/"))
load(paste(dirDat,"pareto.RData",sep="/"))
load(paste(dirDat,"paretoTAC.RData",sep="/"))
```

```{r}
ggplot(pareto[-1,])+
  geom_path(aes(catch5,green))+
  geom_point(aes(catch5,green),data=subset(pareto,X1==70),col="red",size=5)+
  geom_point(data=pM(window(res1[[1]],start=2010),eql[[1]]),aes(catch5,green),col="Blue",size=5)
```


**Figure 1** Pareto

```{r}
ggplot(pareto[-1,])+
  geom_path(aes(catch5,1-aavF*3))+
  geom_point(aes(catch5,1-aavF*3),data=subset(pareto,X1==70),col="red",size=5)+
  geom_point(data=pM(window(res1[[1]],start=2010),eql[[1]]),aes(catch5,1-aavF*3),size=5,col="blue")
```

**Figure 2** Pareto

```{r}
plot(FLStocks("MSE"=res1[[1]],"Counter"=cFac[[70]]))+
  scale_x_continuous(limits=c(2008,2030))
```

**Figure 3** Counterfactual for F=70%FMSY and MSE


